service: user-directory

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  role: userDirectoryServiceDefaultRole
  region: ${opt:region, 'ap-southeast-1'}
  environment:
    ALLOWED_ORIGINS: '.*'

custom:
  environment:
    USER_DIRECTORY_TABLE: ggrasa-user-directory-table
  cors: &cors
    ${file(../serverless-cors.yml)}
  layers: &layers
    ${file(../serverless-layers.yml)}
  resources: &resources
    ${file(./serverless-resources.yml)}

functions:
  getOne:
    handler: handler.getOne
    role: userDirectoryServiceReadRole
    events:
      - http:
          path: userDirectory/{id}
          method: get
          cors: true
    layers:
      -  ${self:custom.layers.default.libs}
  ingest:
    handler: handler.list
    role: userDirectoryServiceReadRole
    events:
      - http:
          path: userDirectory
          method: get
          cors: true
    layers:
      -  ${self:custom.layers.default.libs}

resources:
  ${self:custom.resources.default.resources}